development:
  adapter:  postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool:     <%= ENV['DB_POOL'] %>
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

test:
  adapter:  sqlite3
  database: db/test.sqlite3
  pool:     5
  timeout:  5000

production:
  adapter:  postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool:     <%= ENV['DB_POOL'] %>
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
